# Generated by Django 5.0.1 on 2024-01-31 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('site_admin', '0002_category_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.FileField(upload_to='')),
                ('Price', models.IntegerField()),
                ('Stock', models.CharField(max_length=20)),
                ('Details', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.category_tb')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_tb')),
            ],
        ),
    ]
