# Generated by Django 5.0.1 on 2024-01-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='Details',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='product_tb',
            name='Stock',
            field=models.IntegerField(default='none'),
        ),
    ]
