# Generated by Django 5.0.1 on 2024-02-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_payment_tb'),
        ('seller', '0003_alter_product_tb_details_alter_product_tb_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordertracking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=20)),
                ('Orderdate', models.CharField(max_length=20)),
                ('Ordertime', models.CharField(max_length=20)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.order_tb')),
            ],
        ),
    ]
