# Generated by Django 5.0.1 on 2024-02-07 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_order_tb_orderitems_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_on_card', models.CharField(max_length=20)),
                ('Card_number', models.IntegerField()),
                ('Expiry_date', models.CharField(max_length=20)),
                ('Cvv', models.IntegerField()),
                ('Buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer_tb')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.order_tb')),
            ],
        ),
    ]
